# Some base config
plugin:
  # true - plugin working and checking players. false - plugin ignoring authentication.
  working: true
  # Name that will be displayed near plugin messages
  tab: "ยง4[EasyAuth]"
  # The language in which the plugin will send messages to players. By default, English (en) and Russian (ru) is present.
  # To create your own translation, create a new .yml file in the translations folder, and then copy the values from en.yml there and translate them.
  # Then replace the value of this parameter in the name of the translation file that you created.
  # In the absence of any translations, you will see a message in the console when starting the server.
  language: "en"

# How and where player data will be stored
data:
  # Where to store player data
  dir: "world/playerdata/easy-auth"
  # SHA256 - encoding data in SHA256. no - not encoding data at all (Not recommended)
  method: "SHA256"

# Limits that will be used to players
limits:
  # Time difference limit
  time:
    # If false - will not check time difference on player join
    working: true
    # How much plugin must wait before asking for re-log in minutes
    login_time: 1
  ip:
    # If false - will not check IP difference on player join
    working: true
