name: EasyAuth
version: '${version}'
main: ua.starman.easylogin.EasyAuth
api-version: '1.21'
commands:
  login:
    description: 'Command to log in'
    aliases:
      - 'log'
  register:
    description: 'Command to register'
    aliases:
      - 'reg'
  auth:
    description: 'Command to check auth data'
