name: EasyLogin
version: '${version}'
main: ua.starman.easylogin.EasyLogin
api-version: '1.20'
commands:
  login:
    description: 'Command to log in'
  register:
    description: 'Command to register'
